let Sugestao = [

    "Caçapava", 
    "Igaratá", 
    "Jacareí", 
    "Jambeiro", 
    "Monteiro Lobato",
    "Paraibuna", 
    "Santa Branca", 
    "São José dos Campos",
    "Campos do Jordão",
    "Lagoinha", 
    "Natividade da Serra", 
    "Pindamonhangaba", 
    "Redenção da Serra", 
    "Santo Antônio do Pinhal", 
    "São Bento do Sapucaí",
    "São Luiz do Paraitinga", 
    "Taubaté", 
    "Tremembé",
    "Aparecida",
    "Cachoeira Paulista",
    "Canas",
    "Cunha",
    "Guaratinguetá",
    "Lorena", 
    "Piquete",
    "Potim",
    "Roseira",
    "Arapeí", 
    "Areias", 
    "Bananal",
    "Cruzeiro",
    "Lavrinhas",
    "Queluz", 
    "São José do Barreiro",
    "Silveiras",
    "Caraguatatuba",
    "Ilhabela",
    "São Sebastião",
    "Ubatuba"
];